language: python
branches:
  only:
  - dev
  - master
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - python setup.py install
  - pwd=$PWD
  - cd `python3 -c "import atari_py; import os; print(os.path.dirname(atari_py.__file__))"`
  - cd ale_interface
  - make
  - cd $pwd
script: pytest
