language: python
branches:
  only:
  - dev
  - master
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - python setup.py install
  - cd /usr/local/lib/python3.5/dist-packages/atari_py-0.1.1-py3.5.egg/atari_py/ale_interface/
  - make
  - cd -
script: pytest
