language: python
branches:
  only:
  - dev
  - master
python:
  - "3.5"
install:
  - pwd=$PWD
  - git clone https://github.com/openai/atari-py
  - cd atari-py
  - pip3 install .
  - cd atari_py/ale_interface
  - make
  - cd $pwd
  - pip3 install -r requirements.txt
  - python3 setup.py install
script: pytest
